### PR TITLE
Added removesource.

### PR DESCRIPTION
**Pull request by stephanmg**
Simple removesource command.

### CODE REVIEW

**Comment by stephanmg** [comment]
Patch for issue #4, though one may need a PurgeSource function to remove the source completely form the filesystem. Also a uninstallPackage function to remove / "uninstall" the packages which have been "installed" from a source or removed source would be helpful, cf. #7. (Note: The packages from a removed source already won't be visible anymore to ughub if one remove just the source. However the source is still present on the filesystem in the .ughub dir -- use --force switch to remove also this dir).

**Comment by sreiter** [comment]
Thanks for your proposal! The 'removesource' command would definitively be useful. However, I have some small issues with the current implementation:

Providing a separate 'purgesource' command requires quite some knowledge from the user about the internal structure of ughub's source management. I don't think that this is necessary.

Instead I think the associated local repository should be removed automatically, provided that the following conditions are met:
- [ ] The local repository has an associated (upstream) remote repository.
- [ ] The local repository has no uncommited changes.
- [ ] The local repository has no commits which have not yet been pushed to the remote repository.

If any of those checks fails, an error-message should be printed, together with the hint that the source (and the associated repository) may be removed through specification of the '--force' option.

**Comment by marscher** [comment]
That was quite fast. Thank you!

**Comment by stephanmg** [comment]
Okay, i'll implement the three checks @sreiter. If one of the check fails I'll print an error and suggest using "--force" for removesource command the public API purgesource command will be removed and used internally only.

**Comment by stephanmg** [comment]
Closed in favor for new pull request #12

**Pull request closed without merging**
