### PR TITLE
Tabs and spaces should not be intermixed and spaces are preferred (PEP 8).

### PR DESCRIPTION
**Pull request by stephanmg**
Also, intermixing of spaces and tabs in indenting will prevent to run a given script with the Python 3 interpreter.

### CODE REVIEW

**Comment by sreiter** [comment]
While I appreciate your intention to help in maintaining a tidy code-base, I don't think that this is the best way to approach this issue. Currently we're only using tabs for indentation. To my knowledge 'ughub' works perfectly fine with the python3 interpreter.
If you (and PEP 8) prefer spaces that's fine, however, this should be discussed e.g. in an issue. Until we settled on another way to handle this issue I would appreciate if you could follow the current coding style (i.e. use tabs instead of spaces).

If you're spotting any issues in the current code-base which prevent 'ughub' from running e.g. with the python3 interpreter, please open a new issue.

Thanks again and kind regards,
Sebastian

**Comment by sreiter** [comment]
Didn't want to close the request without you having the opportunity to comment.

**Comment by marscher** [comment]
It it is highly recommendable in terms of readability to use space indention. Almost every Python package follows it and it looks really weird, if one stumbles upon a code which does not follow. It does not hurt to convert this now, does it?

**Comment by stephanmg** [comment]
I see your points, but I also urgue to convert as @marscher. However you may close this issue depending on how you decide @sreiter of course... Best regards

**Comment by sreiter** [comment]
```
                                                                                  Dear @stephanmg, thanks for bringing the issue up. I would prefer to do the conversion myself after thinking and reading about it for a bit. If you don't mind you could close the pull request and open an issue instead.Thanks and kind regards!Sebastian                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Von: Stephan GreinGesendet: Montag, 21. März 2016 17:58An: UG4/ughubAntwort an: UG4/ughubCc: Sebastian ReiterBetreff: Re: [ughub] Tabs and spaces should not be intermixed and spaces are preferred (PEP 8). (#9)I see your points, but I also urgue to convert as @marscher. However you may close this issue depending on how you decide @sreiter of course... Best regards
```

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by stephanmg** [comment]
Update: I reverted all changes in this branch so that only the Tab to Space conversion is left, if you need it, just use this branch _tab_space_fix_ which has already converted the tabs to spaces in the .py files).
Btw I used PyCharm CE to convert which looked promising.

**Pull request closed without merging**
