### PR TITLE
Added purgesource.

### PR DESCRIPTION
**Pull request by stephanmg**
Removes a source from the sources list managed by ughub. May be specified accompanied by the optional switch  **-f** or **--force** => the fetched source is purged in addition from the filesystem.

### CODE REVIEW

**Comment by stephanmg** [comment]
This may close issue #4 after review and could be further enhanced by incorporating the demanded function stated in issue #7 (uninstallPackage) to automatically wipe all "installed" packages from the filesystem.

**Comment by sreiter** [comment]
As I commented on pull-request #6 I don't think its a good idea to provide two different commands to remove a source, since a user can only appreciate the difference through knowledge of the internal source-handling of 'ughub'. Please refer to #6 on how I would approach this issue.

Furthermore, automatically removing all packages that were installed from a given source can be useful but is also very dangerous. I think the only command that should be allowed to actually remove packages is the 'uninstall' command (see #7). One could add an option to this command that removes all packages from a given source. E.g. 'ughub uninstall --allfromsource SomeSource'.

Of course all checks from #7 should be performed on all the installed packages from the specified source.

**Comment by sreiter** [comment]
Didn't want to close the request without you having the opportunity to comment.

**Comment by stephanmg** [comment]
Hey @sreiter. I'll implement this for issue #10 accordingly.

**Comment by stephanmg** [comment]
Closed - will be implemented in issue #10.

**Pull request closed without merging**
