### PR TITLE
added setup script

### PR DESCRIPTION
**Pull request by marscher**
and added import print func from future to improve compat with older python versions.

via the setup script the package is installable via pip:

pip install https://github.com/marscher/ughub@setuptools_pkg

### CODE REVIEW

**Comment by sreiter** [comment]
Thanks for your input! I like the idea that one can simply install ughub through pip. However, there are some issues I've got with the current approach:
- [ ] If somebody doesn't use 'pip' but instead just clones the repo, ughub won't work out of the box anymore. This is important, since some people don't use pip and shouldn't be forced to do so. Please also consider that some people already have cloned the repository and a pull would then make ughub unusable for them.
- [ ] You're adding some dependencies that are not be part of the standard python environment but require some additional libraries (pkg_resources, as far as I understand). Those may be present if pip/setuptools is installed, but as I said, I don't want to force people to use pip.
- [ ] Please keep in mind that ughub has to work on Windows and OSX environments, too.

Do you see a chance to adjust this packaging process so that ughub can be installed through pip and alternatively through a simple repo-clone at the same time?

Thanks and kind regards,
Sebastian

**Comment by marscher** [comment]
On 23.03.2016 13:46, Sebastian Reiter wrote:

> Thanks for your input! I like the idea that one can simply install ughub
> through pip. However, there are some issues I've got with the current
> approach:
> - If somebody doesn't use 'pip' but instead just clones the repo,
>   ughub won't work out of the box anymore. This is important, since
>   some people don't use pip and shouldn't be forced to do so. Please
>   also consider that some people already have cloned the repository
>   and a pull would then make ughub unusable for them.
>   This is doable, if one maps the Python package to the root directory of
>   this repo. However this has the negative side effect of cluttering the
>   site-packages directory in the installation folder (all scripts are in
>   the root of site-packages and not in a separate directory).
> - You're adding some dependencies that are not be part of the standard
>   python environment but require some additional libraries
>   (pkg_resources, as far as I understand). Those may be present if
>   pip/setuptools is installed, but as I said, I don't want to force
>   people to use pip.
>   pkg_resources is part of setuptools, which exists on almost every (sane)
>   Python installation.
> - Please keep in mind that ughub has to work on Windows and OSX
>   environments, too.
>   setuptools takes care of that, because the entry_point console thingy
>   generates launchers for every compatible system.
> 
> Do you see a chance to adjust this packaging process so that ughub can
> be installed through pip and alternatively through a simple repo-clone
> at the same time?
> Yes.

Best regards,
Martin

**Comment by sreiter** [comment]
> pkg_resources is part of setuptools, which exists on almost every (sane) Python installation.

I'll check this. Nevertheless, if it isn't really required then there's no need to add an additional dependency. Or do you see a problem with the way it worked before?

> > - Please keep in mind that ughub has to work on Windows and OSX
> >    environments, too.
> 
> setuptools takes care of that, because the entry_point console thingy
> generates launchers for every compatible system.

But this is only the case if ughub is installed through pip and won't work when doing a simple clone. One could adjust the shell/bat launchers in this case, probably.

**Pull request closed without merging**
